request_server:
  type: ros2
  node_name: inferfw
  services:
    load_model: /inferfw/load_model
    unload_model: /inferfw/unload_model
    infer: /inferfw/infer
    set_task: /inferfw/set_task
    set_operation_mode: /inferfw/set_operation_mode

robot:
  name: g129dof
  action_class: G1Action
  loop_hz: 30.0
  joint_config:
    torso: 6
    right_arm: 7
    left_arm: 7
    right_hand: 12
    left_hand: 12
  topics:
    joint_command:
      topic: /joint/command/joint_state
      message_type: sensor_msgs/JointState
    gripper_command:
      topic: /gripper/command/joint_state
      message_type: sensor_msgs/JointState

pipeline:
  name: g129dof_vla_test1
  preprocess:
    groups:
      - keys:
          - left_img
          - left_wrist_img
          - right_img
          - right_wrist_img
        steps:
          - name: resize
            params:
              width: 224
              height: 224
              mode: bilinear
  models:
    g1_vla:
      runtime: openpi
      config_name: act_g1
      model_path: /workspace/sim_models/act_sim_model/
      input_interface:
        bindings:
          left_img:
            topic: /cam/left/image_raw_color/compressed
            message_type: sensor_msgs/CompressedImage
          left_wrist_img:
            topic: /left_hand/color/image_rect_raw
            message_type: sensor_msgs/Image
          right_img:
            topic: /cam/right/image_raw_color/compressed
            message_type: sensor_msgs/CompressedImage
          right_wrist_img:
            topic: /right_hand/color/image_rect_raw
            message_type: sensor_msgs/Image
          joint_state:
            topic: /joint/state/joint_state
            message_type: sensor_msgs/JointState
      output_interface:
        bindings:
          actions:
            type: joint_trajectory
            groups:
              - torso
              - right_arm
              - left_arm
              - right_hand
              - left_hand
  postprocess:
    groups:
      - keys:
          - actions
        steps:
          - name: resample_action
            params:
              target_hz: 30
              tool_dim: 44
          - name: skip_closest_action
            params:
              tool_dim: 44
              min_remaining: 15
              use_joint_distance: true
          - name: smooth_action
            params:
              dt: 0.033333333333333
              spline_length: 5
              tool_dim: 44
